# Generated by Django 3.1.7 on 2021-02-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(db_index=True, max_length=200)),
                ('protocol', models.CharField(max_length=30)),
                ('precatory', models.CharField(db_index=True, max_length=200)),
                ('situation', models.CharField(db_index=True, max_length=200)),
                ('original_process', models.CharField(db_index=True, max_length=200)),
                ('nature', models.CharField(db_index=True, max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('historical_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_out', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Precatory',
                'verbose_name_plural': 'Precatorys',
            },
        ),
    ]
